workspace:
  path: /go
  base: /src/drone-with-go

pipeline:
  build:
    image: golang
    commands:
      - go build
      - tree
      - pwd
  publish:
    image: plugins/docker
    repo: nodece/test
    secrets: [ docker_username, docker_password ]
